name: Autograder for dynamic linker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # More detail in README.md
      - name: Autograding
        run: |
             make  
             python3 autograder.py

